
# Allow copy to clipboard using prefix (CTRL+B) followed by CTRL+C
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
# Allow pasting from clipboard using prefix (CTRL+B) followed by CTRL+V (NOT NEEDED UNLESS CTRL+SHIFT+V DOESN'T WORK)
# bind C-v run "tmux set-buffer "$(xclip -o -sel clipboard)"; tmux paste-buffer"


unbind r
bind r source-file ~/.tmux.conf

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vi-like keybindings
set-window-option -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g set-clipboard on

# THINK MAC SPECIFIC
# bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

set-option -g history-limit 10000

set -g mouse on
set -g renumber-windows on
set -g allow-rename off
set-window-option -g automatic-rename off

set -g display-panes-active-colour "#5da276"
set -g display-panes-colour "#ffffff"
set -g message-style bg="#5da276",fg="#000000"
set -g mode-style bg="#5da276",fg="#000000"
set -g pane-active-border-style fg="#5da276"
set -g status-style bg="#5da276",fg="#000000"

set -g status-left "#[fg='#000000',bold] Session: #S #[fg='#313244']| #[default]"
set -g status-left-length 40
set -g window-status-format "  #I:#W#{?window_zoomed_flag, +,}  "
set -g window-status-current-format "  #I:#W#{?window_zoomed_flag, +,}  "
set -g window-status-current-style fg="#000000",bg="#ffffff"
set -g window-status-style fg="#000000",bg="#5da276"
set -g status-right "%Y-%m-%d %H:%M"
set -g status-interval 1
