-- Not using for now
-- return {
--   "akinsho/bufferline.nvim",
--   version = "*",
--   dependencies = "nvim-tree/nvim-web-devicons",
--   config = function ()
--     require('bufferline').setup()    
--   end
-- }
--
return {}
